spring:
  application:
    name: YSQL_JPA_Starter
  datasource:
    url: ${DATASOURCE_URL:jdbc:yugabytedb://127.0.0.1:5433/yugabyte}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:com.yugabyte.Driver}
    username: ${DATASOURCE_USERNAME:yugabyte}
    password: ${DATASOURCE_PASSWORD:}
    hikari:
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MINIMUM_IDLE:10}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:0}
      max-lifetime: ${HIKARI_MAX_LIFETIME:14400000} # 4h
      keepalive-time: ${HIKARI_KEEPALIVE_TIME:900000} # 15m
      transaction-isolation: ${HIKARI_TRANSACTION_ISOLATION:TRANSACTION_READ_COMMITTED}
      connection-init-sql: ${HIKARI_CONNECTION_INIT_SQL:}
      data-source-properties:
        currentSchema: ${YSQL_CURRENT_SCHEMA:test2}
        loginTimeout: ${YSQL_LOGIN_TIMEOUT:0} # default 0s
        connectTimeout: ${YSQL_CONNECT_TIMEOUT:15} # default 10s
        socketTimeout: ${YSQL_SOCKET_TIMEOUT:10} # default 0s
        options: ${YSQL_OPTIONS:-c statement_timeout=8s}
        prepareThreshold: ${YSQL_PREPARE_THRESHOLD:1}
        additionalEndpoints: ${YSQL_ADDITIONAL_ENDPOINTS:127.0.0.2:5433,127.0.0.3:5433}
        load-balance: ${YSQL_LOAD_BALANCE:true}
        topology-keys: ${YSQL_TOPOLOGY_KEYS:gcp.us-east1.*:1,gcp.us-central1.*:2,gcp.us-west1.*:3}
        fallback-to-topology-keys-only: true
  jpa:
    open-in-view: ${JPA_OPEN_IN_VIEW:false}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}
    properties:
      hibernate:
        generate_statistics: ${HIBERNATE_GENERATE_STATISTICS:false}
        use_sql_comments: ${HIBERNATE_USER_SQL_COMMENTS:false}
        order_inserts: ${HIBERNATE_ORDER_INSERTS:true}
        order_updates: ${HIBERNATE_ORDER_UPDATES:true}
        #connection.handling_mode: ${HIBERNATE_CONNECTION_HANDLING_MODE:DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION}
        # ^^^ TODO this breaks read only semantics see https://vladmihalcea.com/spring-transaction-connection-management/
  #        temp:
  #          use_jdbc_metadata_defaults: false <-- todo requires dialect to be specified
  #        jdbc:
  #          batch_size: ${HIBERNATE_BATCH_SIZE:50}
  #          use_scrollable_resultset: true
  #          use_get_generated_keys: true
  flyway:
    default-schema: ${DATABASE_SCHEMA:test2}
    user: ${FLYWAY_USERNAME:yugabyte}
    password: ${FLYWAY_PASSWORD:}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
    mixed: true # non-transactional
    placeholders:
      env: qa
      ybIndexMode: concurrently
      deviceCount: 5000
      mediaPerDeviceCount: 60
  retry:
    max-attempts: ${YSQL_RETRY_MAX_ATTEMPTS:5}
    backoff-initial-interval: ${YSQL_BACKOFF_INIT_INTERVAL_MS:2}
    backoff-multiplier: ${YSQL_BACKOFF_MULTIPLIER_MS:8}
    backoff-max-interval: ${YSQL_BACKOFF_MAX_INTERVAL_MS:3000}

server:
  error:
    include-stacktrace: never # override devtools behavior

# TODO copy/move most of these to local
logging.level:
  com.zaxxer.hikari: ${HIKARI_LOG_LEVEL:TRACE}
  com.zaxxer.hikari.HikariConfig: ${HIKARI_CONFIG_LOG_LEVEL:DEBUG}
  com.yugabyte: ${YSQL_LOG_LEVEL:INFO}
  com.yugabyte.Driver: ${YSQL_DRIVER_LOG_LEVEL:TRACE}
  org.hibernate.SQL: ${HIBERNATE_SQL_LOG_LEVEL:DEBUG}
  org.hibernate.cfg: ${HIBERNATE_CONFIG_LOG_LEVEL:DEBUG}
  org.hibernate.type.descriptor.sql: ${HIBERNATE_SQL_PARAMS_LOG_LEVEL:TRACE}
  org.springframework.retry.support.RetryTemplate: ${SPRING_RETRY_LOG:DEBUG}