###
### Profile for use when doing local development.
###
### In IntelliJ, just add "local" to the Active Profiles of the Run/Debug
### profile of the IDE.
###

# Add db/testing path for additional migration scripts, presumable for loading
# repeatable test data.
# Sets default user to local/local
spring:
  flyway:
    locations: classpath:db/migration,classpath:db/testing
  security:
    user:
      name: local
      password: local

# Allow devtools to put full stack traces in REST response body (local only!)
server:
  error:
    include-stacktrace: always

# Enable all Actuator endpoints when running locally
management:
  endpoints:
    web:
      exposure:
        include: "*"