##
## TODO this is still a work in progress for hot reloads of TLS on K8s
##
## TODO https://piotrminkowski.com/2024/02/19/spring-boot-ssl-hot-reload-on-kubernetes/
## https://www.baeldung.com/spring-boot-security-ssl-bundles
## https://spring.io/blog/2023/11/07/ssl-hot-reload-in-spring-boot-3-2-0
##
spring.ssl.bundle.jks:
  server-certs:
    reload-on-update: true
    keystore:
      location: ${CERT_PATH}/keystore.jks
      password: ${PASSWORD}
      type: JKS
    truststore:
      location: ${CERT_PATH}/truststore.jks
      password: ${PASSWORD}
      type: JKS

server:
  port: ${SEVER_PORT:8443}
  ssl:
    bundle: ${SERVER_SSL_BUNDLE:server-certs}
    client-auth: ${SERVER_CLIENT_AUTH:none}