##
## Profile for Kubernetes environments
##
## This profile enables liveness and readiness probes for Kubernetes and exposes both the health and
## Prometheus endpoint (the later should be secured to not be exposed publicly).
##

management:
  endpoint:
    health.probes.enabled: true
  health.probes:
    livenessstate.enabled: true
    readinessstate.enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus