##
## Profile for Kubernetes (k8s) environments.
##
## This profile enables liveness and readiness probes for Kubernetes and exposes both the health and
## Prometheus endpoint (these should be secured and not be exposed publicly).
##

management:
  endpoint:
    health.probes.enabled: true
  health.probes:
    livenessstate.enabled: true
    readinessstate.enabled: true
  endpoints:
    web.exposure.include: health,prometheus