#
#
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: ysql-jpa-starter-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  DATASOURCE_URL: "jdbc:yugabytedb://10.204.0.20:5433/yugabyte"
  HIKARI_IDLE_TIMEOUT: "0"
  HIKARI_MINIMUM_IDLE: "20"
  HIKARI_MAXIMUM_POOL_SIZE: "20"
  #HIKARI_MAX_LIFETIME: "14400000" # 4h
  #HIKARI_KEEPALIVE_TIME: "600000" # 10m
  HIKARI_VALIDATION_TIMEOUT: "60000"
  HIKARI_LOG_LEVEL: "DEBUG"
  HIKARI_CONFIG_LOG_LEVEL: "DEBUG"
  YSQL_CURRENT_SCHEMA: "samples"
  YSQL_CONNECT_TIMEOUT: "15"
  YSQL_SOCKET_TIMEOUT: "10"
  YSQL_PREPARE_THRESHOLD: "1"
  YSQL_OPTIONS: "-c statement_timeout=8s"
  YSQL_ADDITIONAL_ENDPOINTS: "10.204.0.15:5433,10.204.0.34:5433"
  YSQL_LOAD_BALANCE: "true"
  YSQL_TOPOLOGY_KEYS: "gcp.us-east1.*:1"
  YSQL_DRIVER_LOG_LEVEL: "DEBUG"
  YSQL_PGCONNECTION_LOG_LEVEL: "INFO"
  SERVER_HTTP2_ENABLED: "true"
  SERVER_COMPRESSION_ENABLED: "true"
  SERVER_FORWARD_HEADER_STRATEGY: "native"
  TOMCAT_MAX_CONNECTIONS: "8192"
  TOMCAT_THREADS_MAX: "250"
  TOMCAT_THREADS_MIN_SPARE: "10"
  MANAGEMENT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_WEB_EXPOSURE_INCLUDE: "health,prometheus"