# see https://community.gradle.org/github-actions/docs/setup-gradle/

name: Java CI with Gradle

on:
  push:
  pull_request:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary-as-pr-comment: on-failure
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports
          path: build/reports/
